services:
  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: router
    restart: unless-stopped
    networks:
      - global-net
      - local-net
    environment:
      NAME: "test"
      GLOBAL_NATS: "nats://nats-global:4222"
      GLOBAL_STREAM: "FUNCTIONS"
      GLOBAL_TOPIC: "functions.test"
      LOCAL_TOPIC: "fn"
      SHARDS: 1


  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    container_name: stateless_processor
    restart: unless-stopped
    networks:
      - local-net
    environment:
      NAME: "test_processor"
      NATS_ADDR: "nats://router:4222"
      SUB_TOPICS: "fn.0"
      PUB_TOPIC: "fn.out"
      DLQ_TOPIC: "fn.dlq"
    depends_on:
      router:
        condition: service_started

networks:
  local-net:
    driver: bridge
  global-net:
    external: true