services:
  local-nats:
    image: nats:latest
    container_name: local-nats
    restart: unless-stopped
    command: ["-js"]
    networks:
      - local-net

  router:
    build:
      context: router
      dockerfile: router/Dockerfile
    container_name: router
    restart: unless-stopped
    networks:
      - global-net
      - local-net
    environment:
      NAME: "test"
      GLOBAL_NATS: "nats://nats-global:4222"
      GLOBAL_STREAM: "FUNCTIONS"
      GLOBAL_TOPIC: "FUNCTIONS.test"
      LOCAL_NATS: "nats://local-nats:4222"
      LOCAL_TOPIC: "fn"
      SHARDS: 1
    depends_on:
      local-nats:
        condition: service_started
      processor:
        condition: service_started


  processor:
    build:
      context: processor
      dockerfile: processor/Dockerfile
    container_name: stateless_processor
    restart: unless-stopped
    networks:
      - local-net
    environment:
      NAME: "test_processor"
      NATS_ADDR: "nats://local-nats:4222"
      SUB_TOPICS: "fn.0"
      PUB_TOPIC: "fn.out"
      DLQ_TOPIC: "fn.dlq"
    depends_on:
      local-nats:
        condition: service_started

networks:
  local-net:
    driver: bridge
  global-net:
    external: true